name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests